name: Wine-Quality

on: push

jobs:
  name: wine
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2
    - name: wine-train
      env: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run:
        pip install -r requirments.txt
        python train.py
        
        
        echo "## model metrics" > report.md
        cat metrics.txt >> report.md
        
        echo "## data vizz" >> report.md
        cml-publish feature_importtance.png --md >> report.md
        cml-publish residuasl.png >> report.md
        
        cml send-comment report.md
      
    
